server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/supply_ai?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost


#开启驼峰命名和下划线命名的转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

#logging:
#  level:
#    root: debug
#    sql: debug

logging:
  level:
    org.mybatis: DEBUG
    com.example.mapper: DEBUG
    springboot.example.supplyAi.mapper: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
